from improvelib.utils import str2bool

preprocess_params = [

    {"name": "y_data_file",
     "type": str,
     "default": "synergy.tsv",
     "help": "name of y data file",
    },
    {"name": "cell_data_file",
     "type": str,
     "default": "transcriptomics_L1000.tsv",
     "help": "name of y data file",
    },
    {"name": "drug_data_file",
     "type": str,
     "default": "drug_mordred.tsv",
     "help": "name of y data file",
    },
    {"name": "datasets",
     "type": str,
     "default": "ALMANAC",
     "help": "datasets to use -- currently not used",
    },
]
train_params = [
    {"name": "gpu-devices",
     "type": str,
     "default": "0",
     "help": "gpu device ids for CUDA_VISIBLE_DEVICES",
    },
    {"name": "gpu-support",
     "type": str2bool,
     "default": True,
     "help": "Use GPU support or not",
    },
    {"name": "num_cores",
     "type": int,
     "default": 8,
     "help": "num_cores",
    },
    {"name": "arch",
     "type": str,
     "default": "matchmaker/architecture.txt",
     "help": "Architecute file to construct MatchMaker layers",
    },
    {"name": "inDrop",
     "type": float,
     "default": 0.0001,
     "help": "inDrop",
    },
    {"name": "drop",
     "type": float,
     "default": 0.5,
     "help": "drop",
    },
]
infer_params = [
    {"name": "gpu-devices",
     "type": str,
     "default": "0",
     "help": "gpu device ids for CUDA_VISIBLE_DEVICES",
    },
    {"name": "gpu-support",
     "type": frm.str2bool,
     "default": True,
     "help": "Use GPU support or not",
    },
    {"name": "num_cores",
     "type": int,
     "default": 8,
     "help": "num_cores",
    },
]